# Generated by Django 2.1.3 on 2019-01-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarious', '0002_auto_20190107_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(default='Jl in aja dulu', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(default='Alex', max_length=100),
            preserve_default=False,
        ),
    ]
