# Generated by Django 2.1.3 on 2019-01-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarious', '0003_auto_20190107_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='code',
            field=models.CharField(default='no-code', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
