# Generated by Django 2.1.3 on 2019-01-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarious', '0004_auto_20190107_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookitem',
            name='book',
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('first_name',)},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='borrowing',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ('-name',)},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='author',
            name='code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='BookItem',
        ),
    ]
