# Generated by Django 2.1.3 on 2019-01-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarious', '0005_auto_20190107_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='back_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
